CREATE TABLE links (
    id SERIAL PRIMARY KEY,
    urlLong VARCHAR(1024) NOT NULL,
    urlShort VARCHAR(255),
    urlQrCode VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiryAt TIMESTAMP,
    views BIGINT DEFAULT 0
);
